// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTKmkMljmbdmS2QcYASxz2EjbVsLD_K8M',
    appId: '1:408119200979:web:0c5fcb93fda986dc2e9826',
    messagingSenderId: '408119200979',
    projectId: 'theworks-35576',
    authDomain: 'theworks-35576.firebaseapp.com',
    storageBucket: 'theworks-35576.firebasestorage.app',
    measurementId: 'G-2538XK9094',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOGvwpLLhP7I2rzxDySqKrNBolqGnkWtw',
    appId: '1:408119200979:android:b86a17502e9e361a2e9826',
    messagingSenderId: '408119200979',
    projectId: 'theworks-35576',
    storageBucket: 'theworks-35576.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpYK3FC70OuGE5Thi4qId0LIjAyM4LeJ0',
    appId: '1:408119200979:ios:021352e9ad412c2f2e9826',
    messagingSenderId: '408119200979',
    projectId: 'theworks-35576',
    storageBucket: 'theworks-35576.firebasestorage.app',
    iosBundleId: 'com.example.theworks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpYK3FC70OuGE5Thi4qId0LIjAyM4LeJ0',
    appId: '1:408119200979:ios:021352e9ad412c2f2e9826',
    messagingSenderId: '408119200979',
    projectId: 'theworks-35576',
    storageBucket: 'theworks-35576.firebasestorage.app',
    iosBundleId: 'com.example.theworks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTKmkMljmbdmS2QcYASxz2EjbVsLD_K8M',
    appId: '1:408119200979:web:d58ce8bb154315632e9826',
    messagingSenderId: '408119200979',
    projectId: 'theworks-35576',
    authDomain: 'theworks-35576.firebaseapp.com',
    storageBucket: 'theworks-35576.firebasestorage.app',
    measurementId: 'G-ML5Z1LWYHK',
  );
}
