import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:theworks/classes/project.dart';
import 'package:theworks/classes/project_service.dart';
import 'package:theworks/classes/application.dart';
import 'package:theworks/theme/app_colors.dart';
import 'package:theworks/routes.dart';

class ProjectDetailScreen extends StatefulWidget {
  final Project project;

  const ProjectDetailScreen({super.key, required this.project});

  @override
  State<ProjectDetailScreen> createState() => _ProjectDetailScreenState();
}

class _ProjectDetailScreenState extends State<ProjectDetailScreen> {
  final ProjectService _projectService = ProjectService();
  final User? _currentUser = FirebaseAuth.instance.currentUser;
  bool _hasApplied = false;
  bool _isApplying = false;

  @override
  void initState() {
    super.initState();
    _checkApplicationStatus();
  }

  Future<void> _checkApplicationStatus() async {
    if (_currentUser != null && widget.project.id != null) {
      final applied = await _projectService.hasApplied(widget.project.id!, _currentUser!.uid);
      if (mounted) {
        setState(() {
          _hasApplied = applied;
        });
      }
    }
  }

  Future<void> _applyForProject() async {
    if (_currentUser == null || widget.project.id == null) return;

    setState(() {
      _isApplying = true;
    });

    try {
      // Fetch more user details if needed, or use Auth defaults
      String studentName = _currentUser!.displayName ?? 'Unknown Student';
      String studentEmail = _currentUser!.email ?? '';

      // Fallback to Firestore if displayName is missing
      if (studentName == 'Unknown Student') {
         final userDoc = await FirebaseFirestore.instance.collection('users').doc(_currentUser!.uid).get();
         if (userDoc.exists) {
           final data = userDoc.data();
           studentName = data?['displayName'] ?? 'Unknown Student';
         }
      }

      final application = Application(
        applicationId: '', // Generated by Firestore
        projectId: widget.project.id!,
        studentId: _currentUser!.uid,
        studentName: studentName,
        studentEmail: studentEmail,
        appliedAt: Timestamp.now(),
        status: 'pending',
      );

      await _projectService.applyForProject(application);

      if (mounted) {
        setState(() {
          _hasApplied = true;
        });
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text("Application submitted successfully!")),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error applying: $e")),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isApplying = false;
        });
      }
    }
  }

  Future<void> _deleteProject() async {
    final confirm = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Project'),
        content: const Text('Are you sure you want to delete this project?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('Delete'),
          ),
        ],
      ),
    );

    if (confirm == true) {
      if (widget.project.id != null) {
        await _projectService.deleteProject(widget.project.id!);
        if (mounted) {
          Navigator.pop(context);
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final isCreator = _currentUser != null && _currentUser!.uid == widget.project.createdBy;

    return Scaffold(
      backgroundColor: AppColors.offWhite,
      appBar: AppBar(
        title: Text(widget.project.name),
        backgroundColor: AppColors.darkBlue,
        foregroundColor: Colors.white,
        actions: [
          if (isCreator) ...[
            IconButton(
              icon: const Icon(Icons.edit),
              onPressed: () {
                Navigator.pushNamed(
                  context,
                  AppRoutes.createProject,
                  arguments: widget.project,
                );
              },
            ),
            IconButton(
              icon: const Icon(Icons.delete),
              onPressed: _deleteProject,
            ),
          ],
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(12),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withValues(alpha: 0.05),
                    blurRadius: 10,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: [
                  _buildInfoItem(Icons.location_on, "Location",
                      "${widget.project.city}\n(${widget.project.locationType})"),
                  Container(width: 1, height: 40, color: Colors.grey.shade300),
                  _buildInfoItem(Icons.timer, "Duration", widget.project.duration),
                ],
              ),
            ),
            const SizedBox(height: 24),
            const Text(
              "Project Description",
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
                color: AppColors.darkBlue,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              widget.project.description,
              style: const TextStyle(
                  fontSize: 16, height: 1.5, color: Colors.black87),
            ),
            const SizedBox(height: 24),
            const Divider(),
            const SizedBox(height: 16),
            const Text(
              "Required Skills",
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
                color: AppColors.darkBlue,
              ),
            ),
            const SizedBox(height: 12),
            Wrap(
              spacing: 8.0,
              runSpacing: 8.0,
              children: widget.project.tags
                  .map((tag) => Chip(
                        label: Text(tag),
                        backgroundColor: AppColors.accentGold,
                        labelStyle: const TextStyle(
                            color: AppColors.darkBlue,
                            fontWeight: FontWeight.w600),
                        side: BorderSide.none,
                      ))
                  .toList(),
            ),
            const SizedBox(height: 40),
            if (isCreator && widget.project.id != null)
              StreamBuilder<List<Application>>(
                stream: _projectService.getApplicationsForProject(widget.project.id!),
                builder: (context, snapshot) {
                  if (snapshot.connectionState == ConnectionState.waiting) {
                    return const Center(child: CircularProgressIndicator());
                  }
                  
                  final applications = snapshot.data ?? [];
                  
                  return Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(color: Colors.grey.shade300),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          "Application Summary: ${applications.length} applicants",
                          style: const TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                            color: AppColors.darkBlue,
                          ),
                        ),
                        if (applications.isNotEmpty) ...[
                          const SizedBox(height: 16),
                          const Divider(),
                          ListView.builder(
                            shrinkWrap: true,
                            physics: const NeverScrollableScrollPhysics(),
                            itemCount: applications.length,
                            itemBuilder: (context, index) {
                              final app = applications[index];
                              return ListTile(
                                leading: const CircleAvatar(child: Icon(Icons.person)),
                                title: Text(app.studentName),
                                subtitle: Text(app.studentEmail),
                                contentPadding: EdgeInsets.zero,
                              );
                            },
                          ),
                        ] else
                          const Padding(
                            padding: EdgeInsets.only(top: 8.0),
                            child: Text(
                              "No applications yet.",
                              style: TextStyle(fontSize: 16, color: Colors.grey),
                            ),
                          ),
                      ],
                    ),
                  );
                }
              )
            else
              SizedBox(
                width: double.infinity,
                height: 50,
                child: ElevatedButton(
                  onPressed: (_hasApplied || _isApplying) ? null : _applyForProject,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: _hasApplied ? Colors.grey : AppColors.darkBlue,
                    foregroundColor: Colors.white,
                    shape: const StadiumBorder(),
                  ),
                  child: _isApplying 
                    ? const SizedBox(width: 24, height: 24, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                    : Text(_hasApplied ? 'Applied' : 'Apply Now',
                      style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                ),
              ),
          ],
        ),
      ),
    );
  }

  // Helper widget to build the icons at the top
  Widget _buildInfoItem(IconData icon, String label, String value) {
    return Column(
      children: [
        Icon(icon, color: AppColors.accentGold, size: 28),
        const SizedBox(height: 4),
        Text(
          label,
          style: const TextStyle(
              fontSize: 12, color: Colors.grey, fontWeight: FontWeight.bold),
        ),
        const SizedBox(height: 2),
        Text(
          value,
          textAlign: TextAlign.center,
          style: const TextStyle(
              fontSize: 14,
              color: AppColors.darkBlue,
              fontWeight: FontWeight.w600),
        ),
      ],
    );
  }
}
